name: CI

on:
  push:
    branches:
      - main  # 或者您选择的主要分支
  pull_request:
    branches:
      - main  # 对于更新的 PR 触发

jobs:
  build:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 环境

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # 检出项目代码

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'  # 根据需要设置您支持的版本，比如 14.x、16.x 或 18.x

      - name: Install dependencies
        run: npm install  # 安装项目依赖

      - name: Run build
        run: npm run build  # 如果有构建步骤，运行构建命令

      - name: Run tests
        run: npm test  # 运行测试命令
